# Generated by Django 4.2.7 on 2023-12-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
