# Generated by Django 4.2.7 on 2023-12-10 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuserprofile_email_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Verification code'),
        ),
    ]
