# Generated by Django 4.2.7 on 2023-12-10 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuserprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserprofile',
            name='email_confirmation_code',
        ),
    ]
