# Generated by Django 4.2.7 on 2023-12-14 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuserprofile_email_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfirmation',
            name='code',
        ),
    ]
