# Generated by Django 4.2.7 on 2023-12-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_emailconfirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Confirmation Code'),
        ),
    ]
