# Generated by Django 4.2.7 on 2023-12-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailconfirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfirmation',
            name='code',
        ),
        migrations.AddField(
            model_name='emailconfirmation',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Activation Code'),
        ),
    ]
