# Generated by Django 4.2.7 on 2023-12-15 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_emailconfirmation_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailConfirmation',
            new_name='AccountActivation',
        ),
    ]
